import time

NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS

MINE_RATE = 4 * SECONDS

STARTING_BALANCE = 1000


MINIING_REWARD = 50

MINIING_REWARD_INPUT = {'address': '---Mining Rewards---'}
