const API_BASE_URL = "http://localhost:5000";

//const API_BASE_URL = "http://BLRL71276.iis.amadeus.net:8080";

const PY_NANOSECONDS = 1;
const PY_MICROSECONDS = 1000 * PY_NANOSECONDS;
const PY_MILLISECONDS = 1000 * PY_MICROSECONDS;

const JS_MILLISECONDS = 1;
const JS_SECONDS = JS_MILLISECONDS * 1000;

export { API_BASE_URL, PY_MILLISECONDS, JS_SECONDS };
